"""
Fix OAuth2 "Error 403: access_denied" by adding yourself as a test user.

Follow these steps to configure the OAuth consent screen properly.
"""

print("=" * 80)
print("OAUTH2 CONSENT SCREEN CONFIGURATION")
print("=" * 80)
print()
print("You're seeing Error 403 because you need to add yourself as a test user.")
print()
print("STEPS TO FIX:")
print("-" * 80)
print()
print("1. Go to: https://console.cloud.google.com/apis/credentials/consent")
print()
print("2. You should see 'OAuth consent screen' configuration")
print()
print("3. Under 'Test users' section:")
print("   - Click '+ ADD USERS'")
print("   - Enter your Gmail address: (the one you want to access)")
print("   - Click 'SAVE'")
print()
print("4. Scroll down and click 'SAVE AND CONTINUE' or 'SAVE'")
print()
print("5. Wait a few seconds, then try running setup_gmail_oauth.py again")
print()
print("=" * 80)
print()
print("FULL OAUTH SETUP CHECKLIST:")
print("-" * 80)
print()
print("□ Created Google Cloud Project")
print("□ Enabled Gmail API:")
print("  → https://console.cloud.google.com/apis/library/gmail.googleapis.com")
print("  → Click 'ENABLE'")
print()
print("□ Configured OAuth consent screen:")
print("  → https://console.cloud.google.com/apis/credentials/consent")
print("  → User Type: External")
print("  → App name: 'Gmail IMAP Client' (or anything)")
print("  → User support email: your email")
print("  → Developer contact: your email")
print("  → Click SAVE AND CONTINUE through all screens")
print()
print("□ Added yourself as test user:")
print("  → In 'Test users' section")
print("  → Click '+ ADD USERS'")
print("  → Add your Gmail address")
print()
print("□ Created OAuth client ID:")
print("  → https://console.cloud.google.com/apis/credentials")
print("  → Click '+ CREATE CREDENTIALS' → 'OAuth client ID'")
print("  → Application type: Desktop app")
print("  → Name: 'Gmail IMAP Desktop'")
print("  → Click CREATE")
print("  → Download JSON and save as 'gmail_credentials.json'")
print()
print("=" * 80)
print()
input("Press Enter once you've added yourself as a test user...")
print()
print("Now run: python setup_gmail_oauth.py")
